set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clear_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ir2_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ir3_IBUF]

set_property PACKAGE_PIN J15 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property PACKAGE_PIN L16 [get_ports clear]
set_property IOSTANDARD LVCMOS33 [get_ports clear]
set_property PACKAGE_PIN V10 [get_ports choose]
set_property IOSTANDARD LVCMOS33 [get_ports choose]
set_property PACKAGE_PIN U11 [get_ports choose2]
set_property IOSTANDARD LVCMOS33 [get_ports choose2]

set_property PACKAGE_PIN P17 [get_ports ir1]
set_property IOSTANDARD LVCMOS33 [get_ports ir1]
set_property PACKAGE_PIN N17 [get_ports ir2]
set_property IOSTANDARD LVCMOS33 [get_ports ir2]
set_property PACKAGE_PIN M17 [get_ports ir3]
set_property IOSTANDARD LVCMOS33 [get_ports ir3]


set_property PACKAGE_PIN H17 [get_ports clkout]
set_property IOSTANDARD LVCMOS33 [get_ports clkout]
set_property PACKAGE_PIN K15 [get_ports Bon]
set_property IOSTANDARD LVCMOS33 [get_ports Bon]

set_property PACKAGE_PIN V11 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property PACKAGE_PIN V12 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN V14 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property PACKAGE_PIN T16 [get_ports ir_no[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ir_no[1]]
set_property PACKAGE_PIN U14 [get_ports ir_no[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ir_no[0]]


#set_property PACKAGE_PIN N14 [get_ports nop]
#set_property IOSTANDARD LVCMOS33 [get_ports nop]
#set_property PACKAGE_PIN R18 [get_ports PAUSE]
#set_property IOSTANDARD LVCMOS33 [get_ports PAUSE]
#set_property PACKAGE_PIN V11 [get_ports hh1]
#set_property IOSTANDARD LVCMOS33 [get_ports hh1]
#set_property PACKAGE_PIN V12 [get_ports hh2]
#set_property IOSTANDARD LVCMOS33 [get_ports hh2]
#set_property PACKAGE_PIN V14 [get_ports hh3]
#set_property IOSTANDARD LVCMOS33 [get_ports hh3]
#set_property PACKAGE_PIN V15 [get_ports hh4]
#set_property IOSTANDARD LVCMOS33 [get_ports hh4]
#set_property PACKAGE_PIN T16 [get_ports hh5]
#set_property IOSTANDARD LVCMOS33 [get_ports hh5]




set_property PACKAGE_PIN J17 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]
set_property PACKAGE_PIN J18 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property PACKAGE_PIN T9 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property PACKAGE_PIN J14 [get_ports an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an[3]]
set_property PACKAGE_PIN P14 [get_ports an[4]]
set_property IOSTANDARD LVCMOS33 [get_ports an[4]]
set_property PACKAGE_PIN T14 [get_ports an[5]]
set_property IOSTANDARD LVCMOS33 [get_ports an[5]]
set_property PACKAGE_PIN K2 [get_ports an[6]]
set_property IOSTANDARD LVCMOS33 [get_ports an[6]]
set_property PACKAGE_PIN U13 [get_ports an[7]]
set_property IOSTANDARD LVCMOS33 [get_ports an[7]]

set_property PACKAGE_PIN T10 [get_ports low[0]]
set_property IOSTANDARD LVCMOS33 [get_ports low[0]]
set_property PACKAGE_PIN R10 [get_ports low[1]]
set_property IOSTANDARD LVCMOS33 [get_ports low[1]]
set_property PACKAGE_PIN K16 [get_ports low[2]]
set_property IOSTANDARD LVCMOS33 [get_ports low[2]]
set_property PACKAGE_PIN K13 [get_ports low[3]]
set_property IOSTANDARD LVCMOS33 [get_ports low[3]]
set_property PACKAGE_PIN P15 [get_ports low[4]]
set_property IOSTANDARD LVCMOS33 [get_ports low[4]]
set_property PACKAGE_PIN T11 [get_ports low[5]]
set_property IOSTANDARD LVCMOS33 [get_ports low[5]]
set_property PACKAGE_PIN L18 [get_ports low[6]]
set_property IOSTANDARD LVCMOS33 [get_ports low[6]]
set_property PACKAGE_PIN H15 [get_ports low[7]]
set_property IOSTANDARD LVCMOS33 [get_ports low[7]]

#set_property PACKAGE_PIN T15 [get_ports cpc[0]]    
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[0]]
#set_property PACKAGE_PIN U14 [get_ports cpc[1]]    
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[1]]
#set_property PACKAGE_PIN T16 [get_ports cpc[2]]   
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[2]]
#set_property PACKAGE_PIN V15 [get_ports cpc[3]]    
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[3]]
#set_property PACKAGE_PIN V14 [get_ports cpc[4]]    
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[4]]
#set_property PACKAGE_PIN V12 [get_ports cpc[5]]    
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[5]]
#set_property PACKAGE_PIN V11 [get_ports cpc[6]]    
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[6]]
#set_property PACKAGE_PIN V16 [get_ports cpc[7]]    
#set_property IOSTANDARD LVCMOS33 [get_ports cpc[7]]

#set_property PACKAGE_PIN T15 [get_ports low[1]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[1]]
#set_property PACKAGE_PIN U14 [get_ports low[2]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[2]]
#set_property PACKAGE_PIN T16 [get_ports low[3]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[3]]
#set_property PACKAGE_PIN V15 [get_ports low[4]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[4]]
#set_property PACKAGE_PIN V14 [get_ports low[5]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[5]]
#set_property PACKAGE_PIN V12 [get_ports low[6]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[6]]
#set_property PACKAGE_PIN V11 [get_ports low[7]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[7]]
#set_property PACKAGE_PIN V16 [get_ports low[0]]    
#set_property IOSTANDARD LVCMOS33 [get_ports low[0]]
