# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu_xdc.xdc

# IP: ip/dist_mem_gen_2/dist_mem_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_2 || ORIG_REF_NAME==dist_mem_gen_2}]

# XDC: ip/dist_mem_gen_2/dist_mem_gen_2_ooc.xdc
