# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu_xdc.xdc

# IP: ip/Ram/Ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ram || ORIG_REF_NAME==Ram}]

# IP: ip/Rom_trap4/Rom_trap4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Rom_trap4 || ORIG_REF_NAME==Rom_trap4}]

# IP: ip/Rom_User/Rom_User.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Rom_User || ORIG_REF_NAME==Rom_User}]

# XDC: ip/Ram/Ram_ooc.xdc

# XDC: ip/Rom_trap4/Rom_trap4_ooc.xdc

# XDC: ip/Rom_User/Rom_User_ooc.xdc
